function blueprint = build_timing_blueprint(ml_trial)
%BUILD_TIMING_BLUEPRINT Build a readable timing plan for one trial.
%
% Input
%   ml_trial : struct returned by ml_prepare_trial()
%
% Output
%   blueprint : struct containing a sequence of trial states

    if ~isstruct(ml_trial)
        error('build_timing_blueprint:InvalidInput', ...
            'ml_trial must be a struct.');
    end

    if ~isfield(ml_trial, 'timing')
        error('build_timing_blueprint:MissingTiming', ...
            'ml_trial must contain a timing field.');
    end

    t = ml_trial.timing;

    states = {};

    states{end+1} = make_state( ...
        'ACQUIRE_FIX', ...
        t.max_acquire_fix_ms, ...
        true, ...
        {'fixation_point'}, ...
        'enter_fix_window');

    states{end+1} = make_state( ...
        'HOLD_FIX', ...
        t.initial_fix_ms, ...
        true, ...
        {'fixation_point'}, ...
        'hold_fix_until_state_end');

    states{end+1} = make_state( ...
        'SHOW_SAMPLE', ...
        t.sample_dur_ms, ...
        true, ...
        {'fixation_point', 'sample_rdk'}, ...
        'hold_fix_until_state_end');

    states{end+1} = make_state( ...
        'DELAY', ...
        t.delay_dur_ms, ...
        true, ...
        {'fixation_point'}, ...
        'hold_fix_until_state_end');

    states{end+1} = make_state( ...
        'SHOW_DISTRACTOR', ...
        t.distractor_dur_ms, ...
        true, ...
        {'fixation_point', 'distractor_rdk'}, ...
        'hold_fix_until_state_end');

    states{end+1} = make_state( ...
        'SHOW_RULE', ...
        0, ...
        true, ...
        {'response_ring', 'rule_cue'}, ...
        'immediate_transition');

    states{end+1} = make_state( ...
        'WAIT_FOR_SACCADE', ...
        t.max_reaction_time_ms, ...
        false, ...
        {'response_ring', 'rule_cue'}, ...
        'make_saccade_to_target');

    states{end+1} = make_state( ...
        'HOLD_TARGET', ...
        t.target_hold_ms, ...
        false, ...
        {'response_ring', 'rule_cue'}, ...
        'hold_gaze_on_target');

    states{end+1} = make_state( ...
        'REWARD', ...
        t.reward_ms, ...
        false, ...
        {'feedback_reward'}, ...
        'deliver_reward');

    states{end+1} = make_state( ...
        'ITI', ...
        t.iti_ms, ...
        false, ...
        {}, ...
        'inter_trial_interval');

    blueprint = struct();
    blueprint.trial_id = get_field_if_present(ml_trial, 'trial_id', NaN);
    blueprint.rule_name = get_field_if_present(ml_trial, 'rule_name', '');
    blueprint.sample_dir = get_field_if_present(ml_trial, 'sample_dir', NaN);
    blueprint.correct_target_angle = get_field_if_present(ml_trial, 'correct_target_angle', NaN);
    blueprint.states = states;
    blueprint.n_states = numel(states);
end


function s = make_state(name, duration_ms, fixation_required, stimuli, transition_rule)
%MAKE_STATE Helper to create one state description.

    s = struct();
    s.name = name;
    s.duration_ms = duration_ms;
    s.fixation_required = fixation_required;
    s.stimuli = stimuli;
    s.transition_rule = transition_rule;
end


function value = get_field_if_present(s, field_name, default_value)
%GET_FIELD_IF_PRESENT Safe field getter.

    if isfield(s, field_name)
        value = s.(field_name);
    else
        value = default_value;
    end
end