function schema = build_behavior_schema()
%BUILD_BEHAVIOR_SCHEMA Define the canonical behavioral data schema.
%
% Output
%   schema : struct describing the expected behavioral fields for one trial
%
% This schema is meant to stay stable across:
%   - offline simulation
%   - future MonkeyLogic runs
%   - downstream analyses

    schema = struct();

    % -------------------------
    % Metadata
    % -------------------------
    schema.metadata = struct();
    schema.metadata.description = 'Canonical behavioral schema for one trial';
    schema.metadata.version = 'v1';

    % -------------------------
    % Condition variables
    % -------------------------
    schema.condition = { ...
        'trial_id', ...
        'rule_id', ...
        'rule_name', ...
        'sample_dir', ...
        'sample_side', ...
        'distractor_dir', ...
        'distractor_side', ...
        'correct_target_angle'};

    % -------------------------
    % Timing variables
    % -------------------------
    schema.timing = { ...
        'max_acquire_fix_ms', ...
        'initial_fix_ms', ...
        'sample_dur_ms', ...
        'delay_dur_ms', ...
        'distractor_dur_ms', ...
        'max_reaction_time_ms', ...
        'target_hold_ms', ...
        'reward_ms', ...
        'error_timeout_ms', ...
        'iti_ms'};

    % -------------------------
    % Response variables
    % -------------------------
    schema.response = { ...
        'response_angle', ...
        'response_correct', ...
        'angular_error_deg'};

    % -------------------------
    % Outcome variables
    % -------------------------
    schema.outcome = { ...
        'final_outcome', ...
        'terminal_state', ...
        'completed'};

    % -------------------------
    % Execution / debug variables
    % -------------------------
    schema.execution = { ...
        'n_states_visited', ...
        'last_state_name'};

    % -------------------------
    % Allowed categorical values
    % -------------------------
    schema.allowed_values = struct();

    schema.allowed_values.rule_name = {'pro', 'anti', 'plus90'};

    schema.allowed_values.final_outcome = { ...
        'correct', ...
        'no_fixation', ...
        'break_fixation', ...
        'no_response', ...
        'wrong_target', ...
        'broke_target_hold', ...
        'internal_error'};

    schema.allowed_values.terminal_state = {'REWARD', 'ERROR'};

    schema.allowed_values.sample_side = [-1, 1];
    schema.allowed_values.distractor_side = [-1, 1];

    % -------------------------
    % Recommended field order
    % -------------------------
    schema.recommended_order = [ ...
        schema.condition, ...
        schema.timing, ...
        schema.response, ...
        schema.outcome, ...
        schema.execution];

end