function inspect_trials()
%INSPECT_TRIALS Build and display a few example trials.

    root_dir = fileparts(mfilename('fullpath'));
    addpath(fullfile(root_dir, 'core'));

    params = default_params();
    trials = build_trial_table(params);

    n_show = min(10, numel(trials));

    fprintf('Showing first %d trials:\n\n', n_show);

    for k = 1:n_show
        fprintf(['trial %d | sample_dir=%3d | sample_side=%2d | ' ...
                 'rule=%s | distractor_dir=%3d | distractor_side=%2d | ' ...
                 'delay=%3d ms | correct_target=%3d\n'], ...
                 trials(k).trial_id, ...
                 trials(k).sample_dir, ...
                 trials(k).sample_side, ...
                 trials(k).rule_name, ...
                 trials(k).distractor_dir, ...
                 trials(k).distractor_side, ...
                 trials(k).delay_dur_ms, ...
                 trials(k).correct_target_angle);
    end
end