function test_sessionlog_to_table()
%TEST_SESSIONLOG_TO_TABLE Unit test for sessionlog_to_table.

    runtime = task_main();
    agent = default_agent();

    sessionlog = run_session_flow(runtime, agent);
    T = sessionlog_to_table(sessionlog);

    assert(istable(T));
    assert(height(T) == sessionlog.n_trials);

    required_vars = { ...
        'trial_id', ...
        'rule_id', ...
        'rule_name', ...
        'sample_dir', ...
        'sample_side', ...
        'distractor_dir', ...
        'distractor_side', ...
        'correct_target_angle', ...
        'final_outcome', ...
        'terminal_state', ...
        'completed', ...
        'response_angle', ...
        'response_correct', ...
        'angular_error_deg', ...
        'n_states_visited', ...
        'last_state_name'};

    assert(all(ismember(required_vars, T.Properties.VariableNames)));

    assert(height(T) == numel(sessionlog.runlogs));
    assert(all(~isnan(T.trial_id)));

    disp('test_sessionlog_to_table passed');
end